# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？


1. boolean代表布尔型数据 
2. float为浮点数数据类型
3. int为整数数据类型


1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [2]:
sums = 0
for i in range(1,100):
    if i%2==0:
        sums -= i
    else:
        sums += i
print(sums)

50


1.3  将字符串 s="yoyo" 转换成列表

In [1]:
s = 'yoyo'
list(s)

['y', 'o', 'y', 'o']

# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

1. 首先range(1,100)生成1-99的数
2. [2::3]表示从第2个数开始取，间隔3个取
3. [-10:]表示取生成的列表的后10个数

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [11]:
class Solution():
    
    def __init__(self,price):
        self.diff = price[0] - price[1]


one = (15,7)
two = (66,20)

print({'one_diff':Solution((15,7)).diff})
print({'two_diff':Solution((66,20)).diff})
#print(Solution((15,7)).__dict__)
#print(Solution((66,20)).__dict__)

{'one_diff': 8}
{'two_diff': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

1. df.columns查看列名
2. df.T进行数据转置

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [9]:
import pandas as pd
import talib as tb

df = pd.read_excel('sz50.xlsx',index_col = 0,sheet_name='600029.XSHG')

close = df['close'].values
print(type(close))
ema = tb.EMA(close,timeperiod=10)
print(ema[-5:])

<class 'numpy.ndarray'>
[ 15.08227205  15.2564044   15.44433088  15.72172526  15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [12]:
df_3 = pd.read_excel('sz50.xlsx',index_col=0,sheet_name=['600029.XSHG','600050.XSHG','601318.XSHG'])
df_panel = pd.Panel(df_3)
df_panel

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume

3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [13]:
arr = df_panel.values
print(arr.shape)
arr[:,-20:,0]

(3, 215, 5)


array([[  13.85,   13.82,   13.83,   14.11,   14.25,   14.39,   15.1 ,
          15.15,   15.22,   14.97,   14.89,   14.99,   14.71,   15.07,
          15.35,   16.  ,   16.04,   16.29,   16.97,   17.05],
       [   8.53,    8.56,    8.62,    8.88,    9.25,    9.24,    9.43,
           9.25,    9.02,    9.15,    9.63,    9.5 ,    9.9 ,    9.97,
           9.96,    9.49,    9.68,    9.61,    9.63,    9.8 ],
       [ 134.83,  134.56,  137.5 ,  143.18,  143.48,  144.15,  143.61,
         143.65,  144.35,  143.36,  146.41,  144.71,  148.56,  156.53,
         157.12,  157.72,  154.99,  163.52,  168.58,  169.57]])

3.5 建立一个5*5的矩阵，值从0到24

In [14]:
#方法1
[[i*5 + j for j in range(0,5)] for i in range(0,5)]

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [16]:
#方法2
import numpy as np
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])